//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public int IdPelicula { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Duracion { get; set; }
        public int IdGenero { get; set; }
        public string Descripcion { get; set; }
        public int IdPais { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual Genero Genero { get; set; }
        public virtual Pais Pais { get; set; }
    }
}
